SoundPlatform/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('platform_working/', include('platform_working.urls')),
    path('admin/', admin.site.urls)
]

platform_working/urls.py
from django.urls import path

from . import views


app_name = 'platform_working'
urlpatterns = [
    path('', views.index, name='index'),
    path('users/', views.get_all_users, name='all_users'),  # готово
    path('search/', views.search, name='user_search'),  # готово
    path('users/login/', views.hard_login, name='hard_login'),
    path('users/profile/<int:user_id>/', views.profile, name='profile'),  # готово
    path('users/profile/update', views.update_user, name='update_user'),
    path('users/profile/<int:user_id>/delete', views.delete_user, name='delete_user'),
    path('users/create/', views.create_user, name='create_user'),
    path('songs/', views.get_all_songs, name='all_songs'),  # готово
    path('songs/<int:song_id>/', views.get_song_by_id, name='song'),  # готово
    path('songs/<int:song_id>/update', views.update_song, name='update_song'),
    path('songs/<int:song_id>/delete', views.delete_song_by_id, name='delete_song'),
    path('songs/create/', views.create_song, name='create_song'),
    path('albums/', views.get_all_albums, name='all_albums'),  # готово
    path('albums/<int:album_id>/', views.get_album_with_album_list, name='album_list'),  # готово
    path('albums/<int:album_id>/update', views.update_album, name='update_album'),
    path('albums/<int:album_id>/delete', views.delete_album_by_id, name='delete_album'),
    path('albums/create', views.create_album, name='create_album'),
    path('albums/<int:album_id>/create', views.create_album_list, name='create_album_list'),
    path('playlists/', views.get_all_playlists, name='all_playlists'),  # готово
    path('playlists/create', views.create_playlist, name='create_playlist'),
    path('playlists/<int:playlist_id>/', views.get_playlist_with_playlist_list, name='playlist_list'),  # готово
    path('playlists/<int:playlist_id>/update', views.update_playlist, name='update_playlist'),
    path('playlists/<int:playlist_id>/delete', views.delete_playlist_by_id, name='delete_playlist'),
    path('playlists/<int:playlist_id>/create', views.create_playlist_list, name='create_playlist_list'),
    path('groups/', views.get_all_groups, name='all_groups'),  # готово
    path('groups/<int:group_id>/update', views.update_group, name='update_group'),
    path('groups/<int:group_id>/delete', views.delete_group_by_id, name='delete_group'),
    path('groups/<int:group_id>/members/', views.get_users_by_group_id, name='group_members'),  # готово
    path('groups/create', views.create_group, name='create_group'),
    path('users/profile/<int:user_id>/review/create', views.create_review_on_user, name='create_review_on_user'),
    path('users/profile/<int:user_id>/review_create/delete', views.delete_review_on_user, name='delete_review_on_user'),
    path('songs/<int:song_id>/review/create', views.create_review_on_song, name='create_review_on_song'),
    path('songs/<int:song_id>/review_create/delete', views.delete_review_on_song, name='delete_review_on_song'),
    path('users/profile/<int:user_id>/sub', views.create_sub, name='create_sub_on_user'),
    path('users/profile/<int:user_id>/sub/delete', views.delete_sub_on_user, name='delete_sub_on_user'),
    path('groups/<int:group_id>/members/sub', views.create_sub, name='create_sub_on_group'),
    path('groups/<int:group_id>/members/sub/delete', views.delete_sub_on_group, name='delete_sub_on_group'),
    path('songs/<int:song_id>/repost', views.create_repost, name='create_repost'),
    path('songs/<int:song_id>/repost/delete', views.delete_repost, name='delete_repost'),
]

platform_working/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.db.models import Q
from django.urls import reverse
from .forms import *
from .models import Songs
from .models import Users
from .models import Albums
from .models import AlbumList
from .models import Groups
from .models import Playlists
from .models import PlaylistList
from .models import Reposts
from .models import Reviews
from .models import Subscriptions
from datetime import datetime

id_const_user = 1


# Create your views here.
# есть
def index(request):
    """
    будем использовать это, как приветственную страницу
    то есть - при попадании на эту страницу, пользователю будет предложено пройти авторизацию
    если же он уже авторизирован, будет осуществлен переход на глвную страницу
    """
    return render(request, 'platform_working/index.html')


#  готово (и метод, и шаблон)
def profile(request, user_id):
    """
    в своём профиле авторизированный пользователь должен видеть все свои песни, подписки, альбомы, репосты
    """
    response = Songs.objects \
        .select_related('id_user').all() \
        .values('song_title', 'id_user__login', 'id_user__albums__album_title') \
        .filter(id_user=user_id)
    songs = get_songs_by_user_id(request, user_id)
    albums = get_album_by_user_id(request, user_id)
    playlists = Playlists.objects.all().filter(id_user__playlists=user_id)
    user = Users.objects.values('login', 'id_user').get(id_user=user_id)
    subs = Subscriptions.objects.filter(id_follower=user_id).values('id_user__groups__group_title', 'id_user__login',
                                                                    'id_user', 'id_group')
    revs = Reviews.objects.filter(id_user=user_id).all()
    lst = []
    for rev in revs:
        if rev.id_song is None:
            reviews = Reviews.objects.filter(id_review=rev.id_review).values('id_reviewer__login', 'text', 'date',
                                                                             'id_song', 'id_review',
                                                                             'id_reviewer').get()
            lst.append(reviews)
    reposts = Reposts.objects.filter(id_reposter=user_id).all().order_by('id_repost')
    reposted_songs = []
    for song in reposts:
        reposted_songs.append(Songs.objects.filter(id_song=song.id_song).values('id_song', 'id_user', 'id_user__login',
                                                                                'song_title').get())
    global id_const_user
    flag = True
    if user_id == id_const_user:
        flag = False
    subs_temp = Subscriptions.objects.filter(id_user=user_id)
    if subs_temp is not None:
        for i in subs_temp:
            if i.id_follower.id_user == id_const_user and i.id_group is None:
                flag = False
                break
    else:
        if user_id == id_const_user:
            flag = False

    if user_id == id_const_user:
        if not flag:
            context = {
                "lst": response,
                "songs": songs,
                "albums": albums,
                "playlists": playlists,
                "user": user,
                "subs": subs,
                "reviews": lst,
                "reposts": reposts,
                "reposted_songs": reposted_songs,
                "id_const": id_const_user
            }
        else:
            context = {"lst": response, "songs": songs, "albums": albums, "playlists": playlists,
                       "user": user, "subs": subs, "reviews": lst, "reposts": reposts, "reposted_songs": reposted_songs,
                       "id_const": id_const_user, "sub": 1}
    else:
        if flag:
            context = {"lst": response, "songs": songs, "albums": albums, "playlists": playlists,
                       "user": user, "subs": subs, "reviews": lst, "reposts": reposts, "reposted_songs": reposted_songs,
                       "sub": 1}
        else:
            context = {"lst": response, "songs": songs, "albums": albums, "playlists": playlists,
                       "user": user, "subs": subs, "reviews": lst, "reposts": reposts, "reposted_songs": reposted_songs,
                       "del_sub": 1}
    return render(request, 'platform_working/profile.html', context=context)


#  если оно будет работать всегда, то это успех
def hard_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            global id_const_user
            id_const_user = Users.objects.get(email=form.cleaned_data['email']).id_user
            return HttpResponseRedirect(reverse('platform_working:profile', args=(id_const_user,)))
        else:
            print(form.cleaned_data)
    else:
        form = LoginForm()
    context = {'form': form}
    return render(request, 'platform_working/login.html', context=context)


#  готово (и метод, и шаблон)
def search(request):
    query = request.GET.get('q')
    users = get_user_by_login(request, query)
    songs = get_songs_by_title(request, query)
    albums = get_albums_by_title(request, query)
    playlists = get_playlists_by_title(request, query)
    groups = get_groups_by_title(request, query)
    global id_const_user
    context = {
        "users": users,
        "songs": songs,
        "albums": albums,
        "playlists": playlists,
        "groups": groups,
        "id_const": id_const_user
    }
    return render(request, 'platform_working/user_search.html', context)


#  готово (и метод, и шаблон)
def get_all_users(request):
    """
    вывод всех пользователей
    """
    response = Users.objects.all()
    global id_const_user
    context = {"lst": response, "id_const": id_const_user}
    return render(request, 'platform_working/all_users.html', context)


#  используется
def get_user_by_login(request, login):
    """
    поиск пользователей по логину
    """
    res = Users.objects.all().filter(
        Q(login__icontains=login)
    )
    return res


# готово (и метод, и шаблон)
def create_user(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            u = Users.objects.get(login=form.cleaned_data['login'])
            global id_const_user
            id_const_user = u.id_user
            return HttpResponseRedirect(reverse('platform_working:profile', args=(u.id_user,)))
    else:
        form = RegisterForm()
    context = {'form': form}
    return render(request, 'platform_working/new_user.html', context=context)


#  живём
def update_user(request):
    global id_const_user
    user = Users.objects.get(id_user=id_const_user)
    form = UpdateUserForm(request.POST or None, instance=user)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('platform_working:profile', args=(id_const_user,)))
    return render(request, 'platform_working/update_user.html', context={'form': form})


#  готово (но может и нет, надо пробовать)
def delete_user(request):
    global id_const_user
    users_to_delete = Subscriptions.objects.filter(id_user=id_const_user)
    for user in users_to_delete:
        user.delete()
    users_to_delete = Groups.objects.filter(id_user=id_const_user)
    for user in users_to_delete:
        user.delete()
    users_to_delete = Reposts.objects.filter(id_user=id_const_user)
    for user in users_to_delete:
        user.delete()
    users_to_delete = Reviews.objects.filter(id_user=id_const_user)
    for user in users_to_delete:
        user.delete()
    users_to_delete = Albums.objects.filter(id_user=id_const_user)
    id_al = Albums.objects.filter(id_user=id_const_user)
    for i in id_al:
        lst = AlbumList.objects.filter(id_album=i.id_album)
        for j in lst:
            j.delete()
        i.delete()
    users_to_delete = Playlists.objects.filter(id_user=id_const_user)
    id_al = Playlists.objects.filter(id_user=id_const_user)
    for i in id_al:
        lst = PlaylistList.objects.filter(id_album=i.id_playlist)
        for j in lst:
            j.delete()
        i.delete()
    users_to_delete = Songs.objects.filter(id_user=id_const_user)
    for song in users_to_delete:
        song.delete()
    Users.objects.get(id_user=id_const_user).delete()
    return render(request, 'platform_working/index.html')


#  готово (и метод, и шаблон)
def get_all_songs(request):
    """
    вывод всех песен
    """
    res = Songs.objects.all()
    global id_const_user
    return render(request, 'platform_working/all_songs.html', context={"lst": res, "id_const": id_const_user})


#  используется
def get_songs_by_title(request, title):
    res = Songs.objects.all().filter(
        Q(song_title__icontains=title)
    )
    return res


#  используется
def get_songs_by_user_id(request, user_id):
    res = Songs.objects.all().filter(id_user=user_id)
    return res


#  готово (и метод, и шаблон)
def get_song_by_id(request, song_id):
    response = Songs.objects.filter(id_song=song_id).get()
    rev = Reviews.objects.all().filter(id_song=song_id).values('id_reviewer__login', 'text', 'date', 'id_reviewer', 'id_reviewer_id')
    title = Songs.objects.get(id_song=song_id)
    user = Users.objects.filter(id_user=title.id_user.id_user).get()
    albums = AlbumList.objects.filter(id_song=song_id).values('id_album__album_title', 'id_album')
    mixes = PlaylistList.objects.filter(id_song=song_id).values('id_playlist__playlist_title', 'id_playlist')
    time = response.time.strftime("%H:%M:%S")
    global id_const_user
    if user.id_user == id_const_user:
        context = {'song': response, 'reviews': rev, 'title': title, 'albums': albums,
                   'playlists': mixes, 'author': user, 'time': time, 'id_const': id_const_user}
    else:
        rep = Reposts.objects.filter(id_reposter=id_const_user, id_song=song_id)
        print(rep)
        if rep.count() == 0:

templates/platform_working/group_members.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <title>Члены сообщества</title>
</head>
<body>
<header>
    <div style="background-color: cornflowerblue">
        <img src="https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/418f0a68688713.5b65b8eda5782.png"
             class="rounded mx-auto d-block" width="300" height="200">
    </div>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">
                <img src="https://static-s.aa-cdn.net/img/gp/20600005690568/msPaM0DBaJ16mp8SbexZaO10WD18zek3PoYZ_NzOfp0q50wYQiY4R8DZZqRXQ9N5bnY4=w300?v=1"
                     alt="" width="30" height="30">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" aria-current="page" href={% url "platform_working:all_users" %}>Пользователи</a>
                    <a class="nav-link" href={% url "platform_working:all_songs" %}>Песни</a>
                    <a class="nav-link" href={% url "platform_working:all_albums" %}>Альбомы</a>
                    <a class="nav-link" href={% url "platform_working:all_playlists" %}>Плейлисты</a>
                    <a class="nav-link" href={% url "platform_working:all_groups" %}>Сообщества</a>
                </div>
            </div>
        </div>
    </nav>
    {% if title %}
        <div>
            <img src="https://img.favpng.com/9/13/15/computer-icons-symbol-icon-design-png-favpng-dwyij4WSdArzhDxL0M9X6mejB.jpg"
                 alt="group" width="100" height="100">
            <p>
            <h2>
                {{ title }}
            </h2>
            </p>
            {% if user %}
                <p>
                    Создатель:
                    <img src="https://pixelbox.ru/wp-content/uploads/2021/05/ava-vk-animal-91.jpg"
                         alt="user" width="30" height="30">
                    <a href={% url 'platform_working:profile' user.id_user %} class="link-dark">
                        {{ user.login }}
                    </a>
                </p>
            {% endif %}
        </div>
    {% endif %}
</header>
{% if group %}
    {% if id_const %}
        <a href="{% url 'platform_working:create_sub_on_group' id_g %}">
            <button type="button" class="btn btn-success">Подписаться</button>
        </a>
        <a href="{% url 'platform_working:delete_sub_on_group' id_g %}">
            <button type="button" class="btn btn-danger">Отписаться</button>
        </a>
    {% endif %}
    {% if id_g %}
        <a href="{% url 'platform_working:update_group' id_g %}">
            <button type="button" class="btn btn-info">Изменить</button>
        </a>
    {% endif %}
    <ul class="list-unstyled">
        <h4>Подписчики: </h4>
        {% for follower in group %}
            <li>
                <div>
                    <img src="https://pixelbox.ru/wp-content/uploads/2021/05/ava-vk-animal-91.jpg"
                         alt="follower" width="60" height="60">
                    <a href={% url 'platform_working:profile' follower.id_follower %} class="link-dark">
                        {{ follower.id_follower__login }}
                    </a>
                </div>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <h3>В это сообщество ещё никто не вступил. Будьте первыми!</h3>
    {% if id_const %}
        <a href="{% url 'platform_working:create_sub_on_group' id_g %}">
            <button type="button" class="btn btn-success">Подписаться</button>
        </a>
    {% endif %}
{% endif %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous">
</script>
</body>
</html>

templates/platform_working/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <title>Профиль пользователя</title>
</head>
<body>
<header>
    <div style="background-color: cornflowerblue">
        <img src="https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/418f0a68688713.5b65b8eda5782.png"
             class="rounded mx-auto d-block" width="300" height="200">
    </div>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">
                <img src="https://static-s.aa-cdn.net/img/gp/20600005690568/msPaM0DBaJ16mp8SbexZaO10WD18zek3PoYZ_NzOfp0q50wYQiY4R8DZZqRXQ9N5bnY4=w300?v=1"
                     alt="" width="30" height="30">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" aria-current="page" href={% url "platform_working:all_users" %}>Пользователи</a>
                    <a class="nav-link" href={% url "platform_working:all_songs" %}>Песни</a>
                    <a class="nav-link" href={% url "platform_working:all_albums" %}>Альбомы</a>
                    <a class="nav-link" href={% url "platform_working:all_playlists" %}>Плейлисты</a>
                    <a class="nav-link" href={% url "platform_working:all_groups" %}>Сообщества</a>
                </div>
            </div>
            {% if id_const %}
                <div class="navbar-nav" align="left">
                    <a class="nav-link" aria-current="page" href={% url "platform_working:index" %}>Выйти</a>
                </div>
            {% endif %}
        </div>
    </nav>
    {% if user %}
        <div align="center" style="background-color: bisque">
            <img src="https://pixelbox.ru/wp-content/uploads/2021/05/ava-vk-animal-91.jpg"
                 alt="user" width="70" height="70">
            <p>
            <h2>
                {{ user.login }}
            </h2>
            </p>
        </div>
    {% endif %}
    {% if sub %}
        <a href="{% url 'platform_working:create_sub_on_user' user.id_user %}">
            <button type="button" class="btn btn-success">Подписаться</button>
        </a>
    {% endif %}
    {% if del_sub %}
        <a href="{% url 'platform_working:delete_sub_on_user' user.id_user %}">
            <button type="button" class="btn btn-danger">Отписаться</button>
        </a>
    {% endif %}
    {% if id_const %}
        <a href="{% url 'platform_working:update_user' %}">
            <button type="button" class="btn btn-info">Изменить</button>
        </a>
    {% endif %}
</header>
<ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
        <button class="nav-link active" id="songs-tab" data-bs-toggle="tab" data-bs-target="#songs"
                type="button" role="tab" aria-controls="songs" aria-selected="true">Песни
        </button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="albums-tab" data-bs-toggle="tab" data-bs-target="#albums"
                type="button" role="tab" aria-controls="albums" aria-selected="false">Альбомы
        </button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="playlists-tab" data-bs-toggle="tab" data-bs-target="#playlists"
                type="button" role="tab" aria-controls="playlists" aria-selected="false">Плейлисты
        </button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="subs-tab" data-bs-toggle="tab" data-bs-target="#subs"
                type="button" role="tab" aria-controls="subs" aria-selected="false">Подписки
        </button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="reviews-tab" data-bs-toggle="tab" data-bs-target="#reviews"
                type="button" role="tab" aria-controls="reviews" aria-selected="false">Отзывы
        </button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="reposts-tab" data-bs-toggle="tab" data-bs-target="#reposts"
                type="button" role="tab" aria-controls="reposts" aria-selected="false">Репосты
        </button>
    </li>
</ul>
<div class="tab-content" id="userProfile">
    <div class="tab-pane fade show active" id="songs" role="tabpanel" aria-labelledby="songs-tab">
        {% if id_const %}
            <a class="btn btn-success" href={% url 'platform_working:create_song' %} role="button">+ Добавить песню</a>
        {% endif %}
        {% if songs %}
            <ul class="list-unstyled">
                {% for song in songs %}
                    <li>
                        <div>
                            <img src="https://tattoo-stickers.ru/34209-thickbox_default/skripichnyy-kluch.jpg"
                                 alt="metallica" width="70" height="70">
                            <a href={% url 'platform_working:song' song.id_song %} class="link-dark">
                                {{ song.song_title }}
                            </a>
                        </div>
                    </li>
                    <li></li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No songs are available.</p>
        {% endif %}
    </div>
    <div class="tab-pane fade" id="albums" role="tabpanel" aria-labelledby="albums-tab">
        {% if id_const %}
            <a class="btn btn-success" href={% url 'platform_working:create_album' %} role="button">+ Добавить
                альбом</a>
        {% endif %}
        {% if albums %}
            <ul class="list-inline">
                {% for album in albums %}
                    <li class="list-inline-item">
                        <img src="https://e7.pngegg.com/pngimages/291/730/png-clipart-computer-icons-album-music-music-box-classic-album-photography.png"
                             alt={{ album.album_title }} width="100" height="100">
                        <p>
                            <a href={% url "platform_working:album_list" album.id_album %} class="link-dark">
                                {{ album.album_title }}
                            </a>
                        </p>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No albums are available.</p>
        {% endif %}
    </div>
    <div class="tab-pane fade" id="playlists" role="tabpanel" aria-labelledby="playlists-tab">
        {% if id_const %}
            <a class="btn btn-success" href={% url 'platform_working:create_playlist' %} role="button">+ Создать
                плейлист</a>
        {% endif %}
        {% if playlists %}
            <ul class="list-inline">
                {% for playlist in playlists %}
                    <li class="list-inline-item">
                        <img src="https://cdn.pixabay.com/photo/2021/01/08/14/44/cd-5900095_1280.png"
                             alt={{ playlist.playlist_title }} width="100" height="100">
                        <p>
                            <a href={% url "platform_working:playlist_list" playlist.id_playlist %} class="link-dark">
                                {{ playlist.playlist_title }}
                            </a>
                        </p>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No playlists are available.</p>
        {% endif %}
    </div>
    <div class="tab-pane fade" id="subs" role="tabpanel" aria-labelledby="subs-tab">
        {% if subs %}
            <ul class="list-inline">
                {% for sub in subs %}
                    <li>
                        <p>
                            {% if sub.id_group != null %}
                                <img src="https://img.favpng.com/9/13/15/computer-icons-symbol-icon-design-png-favpng-dwyij4WSdArzhDxL0M9X6mejB.jpg"
                                     alt="group" width="80" height="80">
                                <a href={% url "platform_working:group_members" sub.id_group %} class="link-dark">
                                    {{ sub.id_user__groups__group_title }}
                                </a>
                            {% else %}
                                <img src="https://pixelbox.ru/wp-content/uploads/2021/05/ava-vk-animal-91.jpg"
                                     alt="user" width="70" height="70">
                                <a href={% url "platform_working:profile" sub.id_user %} class="link-dark">
                                    {{ sub.id_user__login }}
                                </a>
                            {% endif %}
                        </p>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No playlists are available.</p>
        {% endif %}
    </div>
    <div class="tab-pane fade" id="reviews" role="tabpanel" aria-labelledby="reviews-tab">
        {% if not id_const %}
            <a class="btn btn-success"
               href={% url 'platform_working:create_review_on_user' user.id_user %} role="button">Написать
                отзыв</a>
        {% endif %}
        {% if reviews %}
            <ul class="list-unstyled">
                {% for review in reviews %}
                    <li>
                        <div>
                            <figure>
                                <blockquote class="blockquote">
                                    <p>{{ review.text }}</p>
                                </blockquote>
                                <figcaption class="blockquote-footer">
                                    <a href={% url 'platform_working:profile' review.id_reviewer %} class="link-dark">
                                        {{ review.id_reviewer__login }}</a> <cite
                                        title="Date">{{ review.date }}</cite>
                                </figcaption>
                            </figure>
                        </div>
                        {% if review.id_reviewer.id_user == id_const %}
                            <a href="{% url 'platform_working:delete_review_on_user' user.id_user %}">
                                <button type="button" class="btn btn-danger">Удалить</button>
                            </a>
                        {% endif %}
                    </li>
                    <li></li>
                {% endfor %}
            </ul>
        {% else %}
            <p>Отзывов пока нет, будьте первыми!</p>
        {% endif %}
    </div>
    <div class="tab-pane fade" id="reposts" role="tabpanel" aria-labelledby="reposts-tab">
        {% if reposts %}
            <ul class="list-unstyled">
                {% for repost in reposts %}
                    <li>
                        <div>
                            {% for song in reposted_songs %}
                                {% if song.id_song == repost.id_song %}
                                    <figure>
                                        <blockquote class="blockquote">
                                            {% if repost.text != null %}
                                                <p>"{{ repost.text }}"</p>
                                            {% else %}
                                                <p> ---- </p>
                                            {% endif %}
                                        </blockquote>
                                        <figcaption class="blockquote-footer">
                                            <img src="https://tattoo-stickers.ru/34209-thickbox_default/skripichnyy-kluch.jpg"
                                                 alt="metallica" width="50" height="50">
                                            <a href={% url 'platform_working:song' song.id_song %} class="link-dark">
                                                {{ song.song_title }}
                                            </a>
                                            <a href="{% url 'platform_working:delete_repost' song.id_song %}">
                                                <button type="button" class="btn btn-danger">Удалить репост</button>
                                            </a>
                                        </figcaption>
                                    </figure>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>Пользователь не добавил ни одной песни</p>
        {% endif %}
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous">
</script>
</body>
</html>